#[cfg(target_os = "macos")]
fn parse_modifier_key(value: &str) -> Result<MacKey> {
    match parse_key(value)? {
        key if key.is_modifier() => Ok(key),
        _ => bail!("mouse action modifiers only support Shift / Ctrl / Alt / Command"),
    }
}

#[cfg(target_os = "macos")]
fn parse_key(value: &str) -> Result<MacKey> {
    let normalized = value.trim().to_ascii_uppercase();
    match normalized.as_str() {
        "SHIFT" => Ok(MacKey::Shift),
        "CTRL" | "CONTROL" => Ok(MacKey::Control),
        "ALT" | "OPTION" => Ok(MacKey::Option),
        "META" | "COMMAND" | "CMD" => Ok(MacKey::Command),
        "ENTER" | "RETURN" => Ok(MacKey::Return),
        "TAB" => Ok(MacKey::Tab),
        "SPACE" => Ok(MacKey::Space),
        "ESC" | "ESCAPE" => Ok(MacKey::Escape),
        "BACKSPACE" | "DELETE" => Ok(MacKey::Delete),
        "UP" | "ARROWUP" => Ok(MacKey::Up),
        "DOWN" | "ARROWDOWN" => Ok(MacKey::Down),
        "LEFT" | "ARROWLEFT" => Ok(MacKey::Left),
        "RIGHT" | "ARROWRIGHT" => Ok(MacKey::Right),
        "HOME" => Ok(MacKey::Home),
        "END" => Ok(MacKey::End),
        "PAGEUP" => Ok(MacKey::PageUp),
        "PAGEDOWN" => Ok(MacKey::PageDown),
        "A" => Ok(MacKey::A),
        "B" => Ok(MacKey::B),
        "C" => Ok(MacKey::C),
        "D" => Ok(MacKey::D),
        "E" => Ok(MacKey::E),
        "F" => Ok(MacKey::F),
        "G" => Ok(MacKey::G),
        "H" => Ok(MacKey::H),
        "I" => Ok(MacKey::I),
        "J" => Ok(MacKey::J),
        "K" => Ok(MacKey::K),
        "L" => Ok(MacKey::L),
        "M" => Ok(MacKey::M),
        "N" => Ok(MacKey::N),
        "O" => Ok(MacKey::O),
        "P" => Ok(MacKey::P),
        "Q" => Ok(MacKey::Q),
        "R" => Ok(MacKey::R),
        "S" => Ok(MacKey::S),
        "T" => Ok(MacKey::T),
        "U" => Ok(MacKey::U),
        "V" => Ok(MacKey::V),
        "W" => Ok(MacKey::W),
        "X" => Ok(MacKey::X),
        "Y" => Ok(MacKey::Y),
        "Z" => Ok(MacKey::Z),
        "0" => Ok(MacKey::Digit0),
        "1" => Ok(MacKey::Digit1),
        "2" => Ok(MacKey::Digit2),
        "3" => Ok(MacKey::Digit3),
        "4" => Ok(MacKey::Digit4),
        "5" => Ok(MacKey::Digit5),
        "6" => Ok(MacKey::Digit6),
        "7" => Ok(MacKey::Digit7),
        "8" => Ok(MacKey::Digit8),
        "9" => Ok(MacKey::Digit9),
        other => bail!("unsupported key `{other}`"),
    }
}

#[cfg(target_os = "macos")]
#[derive(Clone, Copy)]
enum MacKey {
    Shift,
    Control,
    Option,
    Command,
    Return,
    Tab,
    Space,
    Escape,
    Delete,
    Up,
    Down,
    Left,
    Right,
    Home,
    End,
    PageUp,
    PageDown,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Digit0,
    Digit1,
    Digit2,
    Digit3,
    Digit4,
    Digit5,
    Digit6,
    Digit7,
    Digit8,
    Digit9,
}

#[cfg(target_os = "macos")]
impl MacKey {
    fn is_modifier(self) -> bool {
        matches!(
            self,
            Self::Shift | Self::Control | Self::Option | Self::Command
        )
    }

    fn code(self) -> u16 {
        match self {
            Self::A => 0,
            Self::S => 1,
            Self::D => 2,
            Self::F => 3,
            Self::H => 4,
            Self::G => 5,
            Self::Z => 6,
            Self::X => 7,
            Self::C => 8,
            Self::V => 9,
            Self::B => 11,
            Self::Q => 12,
            Self::W => 13,
            Self::E => 14,
            Self::R => 15,
            Self::Y => 16,
            Self::T => 17,
            Self::Digit1 => 18,
            Self::Digit2 => 19,
            Self::Digit3 => 20,
            Self::Digit4 => 21,
            Self::Digit6 => 22,
            Self::Digit5 => 23,
            Self::Digit9 => 25,
            Self::Digit7 => 26,
            Self::Digit8 => 28,
            Self::Digit0 => 29,
            Self::O => 31,
            Self::U => 32,
            Self::I => 34,
            Self::P => 35,
            Self::L => 37,
            Self::J => 38,
            Self::K => 40,
            Self::N => 45,
            Self::M => 46,
            Self::Tab => 48,
            Self::Space => 49,
            Self::Delete => 51,
            Self::Return => 36,
            Self::Escape => 53,
            Self::Command => 55,
            Self::Shift => 56,
            Self::Option => 58,
            Self::Control => 59,
            Self::PageUp => 116,
            Self::PageDown => 121,
            Self::End => 119,
            Self::Home => 115,
            Self::Left => 123,
            Self::Right => 124,
            Self::Down => 125,
            Self::Up => 126,
        }
    }
}
